apiVersion: v1
kind: Service
metadata:
  name: server-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: server-app
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30007
